spring.application.name=LibraryManagementAPI
spring.datasource.url=jdbc:mysql://localhost:3306/librarydb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Admin1234!
spring.jpa.hibernate.ddl-auto=update